/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.dinemore.view;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.dinemore.controller.ManageOrderController;
import lk.ijse.dinemore.dto.OrderDTO;
import lk.ijse.dinemore.observer.Observer;

/**
 *
 * @author User
 */
public class Chef_view extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form Chef_view
     */
    public Chef_view() {
        try {
            initComponents();
            getAllOrders();
//
            loadAllOrders();
            UnicastRemoteObject.exportObject(this, 0);
            ManageOrderController.getSubeject().registerObserver(this);
        } catch (RemoteException ex) {
            Logger.getLogger(Chef_view.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Chef_view.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private DefaultTableModel dtm;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblchef = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtoid = new javax.swing.JTextField();
        txtrid = new javax.swing.JTextField();
        txtdate = new javax.swing.JTextField();
        txttime = new javax.swing.JTextField();
        txtcustname = new javax.swing.JTextField();
        txttp = new javax.swing.JTextField();
        txtqty = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );

        jTextField9.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel1.setFont(new java.awt.Font("winnie", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("- CHEF -");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblchef.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Reception ID", "Date", "Time", "Cust Name", "Tell", "QTY"
            }
        ));
        tblchef.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblchefMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblchefMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tblchef);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 30, 798, 171));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel2.setText("ORDERS");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 14, 79, -1));

        jLabel3.setText("ORDER ID");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 208, 84, 36));

        jLabel4.setText("RECEPTION ID");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 276, 84, 36));

        jLabel6.setText("DATE");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 408, 84, 36));

        jLabel7.setText("TIME");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 474, 84, 36));

        jLabel8.setText("CUSTOMER NAME");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 540, 130, 36));

        jLabel9.setText("T.P");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 606, 130, 36));

        jLabel10.setText("QTY");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 672, 130, 36));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("COOK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 135, 39));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("FINISH");
        jPanel7.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 188, 135, 39));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 317, 240, -1));
        jPanel6.add(txtoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 380, 40));
        jPanel6.add(txtrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 380, 40));
        jPanel6.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 390, 40));
        jPanel6.add(txttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 390, 40));
        jPanel6.add(txtcustname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 390, 40));
        jPanel6.add(txttp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, 390, 40));
        jPanel6.add(txtqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 690, 390, 40));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblchefMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblchefMouseClicked
        int selectedrow = tblchef.getSelectedRow();
        String oid = dtm.getValueAt(selectedrow, 0).toString();
        String rid = dtm.getValueAt(selectedrow, 1).toString();
        String date = dtm.getValueAt(selectedrow, 2).toString();
        String time = dtm.getValueAt(selectedrow, 3).toString();
        String cusName = dtm.getValueAt(selectedrow, 4).toString();
        String tell = dtm.getValueAt(selectedrow, 5).toString();
        String qty = dtm.getValueAt(selectedrow, 6).toString();

        txtcustname.setText(cusName);
        txtdate.setText(date);
        txtoid.setText(oid);
        txtrid.setText(rid);
        txttime.setText(time);
        txttp.setText(tell);
        txtqty.setText(qty);
    }//GEN-LAST:event_tblchefMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            String ststus = "Cooking";
            OrderDTO orderDTO = new OrderDTO(
                    txtoid.getText(),
                    txtrid.getText(),
                    txtdate.getText(),
                    txttime.getText(),
                    txtcustname.getText(),
                    txttp.getText(),
                    Integer.parseInt(txtqty.getText()),
                    ststus
            );
            boolean addorder = ManageOrderController.updateCustomer(orderDTO);
            if (addorder) {
                JOptionPane.showMessageDialog(this, "Order has been taken Successfully");
                loadAllOrders();

                getAllOrders();
//                clearText();
            } else {
                JOptionPane.showMessageDialog(this, "Order faild");
            }
        } catch (Exception ex) {
            Logger.getLogger(Chef_view.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblchefMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblchefMouseEntered
//        int selectedRow = tblchef.getSelectedRow();
//        String oid = dtm.getValueAt(selectedRow, 0).toString();
//        String rid = dtm.getValueAt(selectedRow, 1).toString();
//        String date = dtm.getValueAt(selectedRow, 2).toString();
//        String time = dtm.getValueAt(selectedRow, 3).toString();
//        String cusname = dtm.getValueAt(selectedRow, 4).toString();
//        String tp = dtm.getValueAt(selectedRow, 5).toString();
//        String qty = dtm.getValueAt(selectedRow, 6).toString();
//
//        txtoid.setText(oid);
//        txtrid.setText(rid);
//        txtdate.setText(date);
//        txttime.setText(time);
//        txtcustname.setText(cusname);
//        txttp.setText(tp);
//        txtqty.setText(qty);
    }//GEN-LAST:event_tblchefMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chef_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chef_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chef_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chef_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chef_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTable tblchef;
    private javax.swing.JTextField txtcustname;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtoid;
    private javax.swing.JTextField txtqty;
    private javax.swing.JTextField txtrid;
    private javax.swing.JTextField txttime;
    private javax.swing.JTextField txttp;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateObservers() throws Exception {
        loadAllOrders();
//
        getAllOrders();
//        
    }

    private void loadAllOrders() {
        dtm = (DefaultTableModel) tblchef.getModel();
        dtm.setRowCount(0);

        try {
            List<OrderDTO> orders = ManageOrderController.getAllCustomers();
            if (orders == null) {
                return;
            }
            for (OrderDTO order : orders) {
                Object rowdata[] = {
                    order.getOrder_id(),
                    order.getReception_id(),
                    order.getDate(),
                    order.getTime(),
                    order.getCus_name(),
                    order.getTp_no(),
                    order.getQty()
                };
                dtm.addRow(rowdata);
            }
        } catch (Exception ex) {
            Logger.getLogger(Chef_view.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getAllOrders() {
        
        
            dtm = (DefaultTableModel) tblchef.getModel();
        dtm.setRowCount(0);
        try {
            List<OrderDTO> orders = ManageOrderController.getAllCustomers();
            if (orders == null) {
                return;
            }

            for (OrderDTO orderDTO : orders) {
                Object[] rowData = {
                    orderDTO.getOrder_id(),
                    orderDTO.getReception_id(),
                    orderDTO.getDate(),
                    orderDTO.getTime(),
                    orderDTO.getCus_name(),
                    orderDTO.getTp_no(),
                    orderDTO.getQty(),};
                dtm.addRow(rowData);
            }

        } catch (Exception ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    
}
